### ISSUE TITLE
[PE-D][Tester C] Exception message error with regards to price

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-1/tp#153]
UG states that price ranges from 0 to 10000, and I am able to add a price of 0. However, exception message states that price must be greater than 0. 

This exception message is found in all commands that involves price. 

![price.png](https://raw.githubusercontent.com/jeyvia/ped/main/files/96ff8113-9236-46eb-92f8-b0726cdef61f.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: jeyvia/ped#3

**Comment by bdthanh** [comment]
Fixed
