### ISSUE TITLE
[PE-D][Tester E] Add-user problem

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W12-1/tp#156]
![Screen Shot 2022-10-28 at 16.57.26.png](https://raw.githubusercontent.com/zheqis12138/ped/main/files/2c2b6ce0-76e9-4834-b95f-d41facaceb62.png)

can not add user if username comes directly after /n

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: zheqis12138/ped#1

**Comment by bdthanh** [comment]
We added a note in UG to suggest user to put a space between delimiter and value.
