### ISSUE TITLE
[PE-D][Tester C] Data is only saved to files at the end of programme

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-1/tp#162]
Data is only saved to files at the end of programme, or when "bye" command is called. This could pose a great risk if the programme crashes halfway through usage, any updated data will not be saved.

![crash.png](https://raw.githubusercontent.com/jeyvia/ped/main/files/6a0f8859-48d7-4c5d-a175-c06ea4786c02.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: jeyvia/ped#4

**Comment by bdthanh** [comment]
Fixed in the next PR
