### ISSUE TITLE
[PE-D][Tester B] Unable to add username with "/"

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-W12-1/tp#164]
I was unable to add username with "/" inside for example "Jack S/O Hill"

![image.png](https://raw.githubusercontent.com/insafhere/ped/main/files/b202a384-b37f-4434-a85a-9d54132d0ab1.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: insafhere/ped#6

**Comment by bdthanh** [comment]
In UG, we stated that argument value should not contain '/' and '|'. Our app considered this as an argument so that error was printed. User should not use that 2 character in their input value.
