### ISSUE TITLE
[PE-D][Tester E] User guide mistake

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-1/tp#165]
![Screen Shot 2022-10-28 at 17.16.43.png](https://raw.githubusercontent.com/zheqis12138/ped/main/files/fdfd1fd2-0b48-41ef-836a-78cdf9b87d9f.png)

the format have the wrong slash. should be "/" instead of "\"

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: zheqis12138/ped#2

**Comment by bdthanh** [comment]
Same as #148
