### ISSUE TITLE
[PE-D][Tester B] Wrong format of command for finding items using keyword

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-W12-1/tp#170]
Format is supposed to be  : find-item /k [KEYWORD]

![image.png](https://raw.githubusercontent.com/insafhere/ped/main/files/9a9c1773-b4e6-4d06-bd46-ef59f8dd6be9.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: insafhere/ped#8

**Comment by bdthanh** [comment]
Same as #148
