### ISSUE TITLE
Standardize delimiters for Glossary?

### ISSUE THREAD

**Issue by jingwei55** [AY2223S1-CS2113-W12-1/tp#199]
Currently delimiters do not match, sometimes '/n' is used for username, sometimes '/u' is used. Might want to standardise for the glossary

**Comment by bdthanh** [comment]
I think we could add notes in each feature's description, because for example /c is contact number, but it can be category index quite confuse if we combine them and put to glossary

**Comment by jingwei55** [comment]
Was thinking sth like /cn for contact number, /cat for category etc, but might be very troublesome to rewrite all the code. Small issue actually, no time can just dont do

**Comment by chiewyx** [comment]
i think glossary no need add delimiters. I think its for like definitions for any abbreviations we use like tx and ui

**Comment by jingwei55** [comment]
sounds good
