### ISSUE TITLE
tp Code Review - Chien Jing Wei

### ISSUE THREAD

**Issue by wamikamalik** [AY2223S1-CS2113-W12-1/tp#206]
Hi @jingwei55 ! Good job on contributing to the tp. Following are a few comments I have:

- [x] Consider refactoring magic literals for better readability. For example, delimiters such as "u", "i" in view command classes.
- [x] Consider removing commented out code, example line 18 of _ItemList.java_.
- [ ] Consider refactoring repetitive code, example, see line 99 and 108 of _ItemList.java_.

**Comment by jingwei55** [comment]
The 2 lines of code are different, line 98 checks if item is not available while line 107 checks if item is available
