### ISSUE TITLE
Things to do for v1.5

### ISSUE THREAD

**Issue by bdthanh** [AY2223S1-CS2113-W12-1/tp#48]
## All
-	Add javaDoc to all files (all) 

## Bui
-	Storage for User/Item/Transaction (2 people) - Bui
Get all data from file and save to 3 lists when starting the program, and overwrite all data in the files with updated lists. I think we should not edit the files along the way, it's too complicated

## Jing wei
-	Find transaction by status (rcm use Java stream)  (1 person) - Jing wei
find-tx /s finished
find-tx /s unfinished
Exception when status is wrong

## Jorelle
-	Find method for User/Item by keyword (rcm use Java stream) (1 person) - Jorelle
find-user /k [keyword]
find-item /k [keyword]
Exception when keyword is empty

## Yixiang
-	Sort item (use Java stream) (1 person)
sort-items /mode <optional: hl or lh> /min <optional: double> /max / <optional: double>
Exception when mode is unrecognizable (different from “hl” or “lh”)
	     When min is higher than max 
	     When min and max are in wrong format
	     When args are empty
When min or max is less than 0
Note: hl is from high to low, lh is from low to high

## Winston
- Update price and number of days to loan
update-item /i itemID  /p price
update-tx /t transactionId /d newDuration

- Use item ID as well instead of just item name, so more than 1 person can loan the same item

**Comment by jingwei55** [comment]
We can enhance view-user function to display name, borrowed and loaned items

**Comment by jingwei55** [comment]
Small tweak: Add $ sign for pricePerDay

**Comment by winston-lim** [comment]
It seems a bit iffy there is no validation step i.e. users need only pass in their username which is just their full name in PascalCase
In the future, we can think about whether we want a validation step, for example, asking for a user's NRIC(similar to a library), such that only owners of item/transactions can update them

- For now, we simply apply additions/updates/deletes on `Transaction` or `Item` by their `id` without any validation

**Comment by bdthanh** [comment]
Finished
