### ISSUE TITLE
Things to do v2.0b

### ISSUE THREAD

**Issue by bdthanh** [AY2223S1-CS2113-W12-1/tp#49]
Deadline: Friday, 28/10/2022 (before lecture)

- Finish UG 
We need UG before Friday 28th for PED
Format is similar to UG ip (command, description, note, Example, Expected Outcome)
- Polish DG (Introduction, Glossary, Item component, Find user/Item, Duke Architecture...)
- Add JUnit tests for your methods
Aim for at least 50-80% lines of code covered by JUnit tests for each class
- Add JavaDoc to your files 
- Clean code and handle as much exceptions as possible 
- Remove always true assertion, add other one 
- Add Logger

**Comment by chiewyx** [comment]
i think can include find items/users/transactions using keywords

**Comment by bdthanh** [comment]
> i think can include find items/users/transactions using keywords

i put in v1.5

**Comment by chiewyx** [comment]
my bad didnt see that issue

**Comment by jingwei55** [comment]
Can work to store current data into a word file
