### ISSUE TITLE
UX enhancements

### ISSUE THREAD

**Issue by winston-lim** [AY2223S1-CS2113-W12-1/tp#51]
# Overview
Certain improvements can be made for a better user experience

# Features
## Users should see an 'entry point' from greeting message
For example, `type 'help' to list commands`

## List of commands should have some form of organization
We could sort by first character OR group by entity(Command, User, Item, Transaction)

Current state:
![image](https://user-images.githubusercontent.com/64213369/195001214-1b19566a-7ad6-4402-bed4-f3d95aecf41f.png)

## UI is messy
`showLine()` can be improved and also `printMessage()` should have indentations

## Any ID related argument can support entering partial IDs
For example, given `itemId = 6654656257`
`remove-item 56257` can be allowed

## Any list function should support pagination
In the situation where we have >100 entries of an entity, maybe we want 5 pages of 20 entries
- `n` to get to next page
- `p` to get to previous page
- `q` to leave list view

## UI should have a generic showTable function, perhaps `static <T> void showTable(int rowNum, int colNum, <T> entries)`
We can make our list function be a lot more readable in the future

## Others, ignore
- We need to show category mapping OR better yet, a `Category` class which is uniquely identified by `name.toLowerCase().trim()`

**Comment by bdthanh** [comment]
- Currently, we are using item name as its id 
- And we can improve list function by limiting characters of components and padding spaces to it 
- Pagination and indentation sounds nice, we will do that if we have time
